version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    branches:
      only:
      - master
      - /rc-.*/
    working_directory: /tmp/dorious.com
    steps:
    - checkout
    - run: npm install
    - run: npm run test
    - run: npm run build
    - store_artifacts:
        path: /tmp/dorious.com/public