version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    branches:
      only:
      - master
    working_directory: /tmp/dorious.com
    steps:
    - checkout
    - run: 
        name: Install NPM modules
        command: npm install
    - run: 
        name: Run some tests
        command: npm run test
    - run: 
        name: Building
        command: npm run build
    - run: 
        name: Packing
        command: npm pack
    - run: 
        name: Deploying to the server
        command: 
          scp -oStrictHostKeyChecking=no dorious.com-*.tgz circleci@dorious.com:/home/circleci && 
          ssh circleci@dorious.com "tar -zxvf dorious.com-* && rsync --delete -r package/public /var/www/dorious.com/"
    - run:
        name: Clean up
        command:
          ssh circleci@dorious.com "rm -rf dorious.com-*.tgz package/"
          