version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    branches:
      only:
      - master
    working_directory: /tmp/dorious.com
    steps:
    - checkout
    - run: 
        name: Install NPM modules
        command: npm install
    - run: 
        name: Run some tests
        command: npm run test
    - run: npm run build
    - run: 
        name: Packing
        command: npm pack
    # - add_ssh_keys:
    #     fingerprints:
    #     - "31:5c:55:de:71:33:ee:83:ad:fc:51:dd:86:33:52:41"
    - run: 
        name: Deployment to server
        command: 
          scp -oStrictHostKeyChecking=no dorious.com-*.tgz circleci@dorious.com:/home/circleci && 
          ssh circleci@dorious.com "tar -zxvf dorious.com-* && rsync --delete -r package/ /var/www/dorious.com/"
    - run:
        name: Clean up
        command:
          ssh circleci@dorious.com "rm -rf dorious.com-*.tgz package/"
          